name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-compiler-checks
    - name: make
      run: make
    - name: make check
      run: make check
    - name: check_failure
      if: failure()
      run: cat tests/test-suite.log
    - name: make distcheck
      run: make distcheck
