name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure with compiler warnings
      run: ./configure --enable-compiler-warnings
    - name: make with compiler warnings
      run: make
    - name: distclean
      run: make distclean
    - name: configure with checks
      run: ./configure --enable-compiler-checks
    - name: make with compiler checks
      run: make
    - name: make check
      run: make check
    - name: check_failure
      if: failure()
      run: cat tests/test-suite.log
    - name: make distcheck
      run: make distcheck
